### ISSUE TITLE
const TSM.mat4.identity

### ISSUE THREAD

**Issue by adamncasey** [matthiasferch/tsm#5]
I just got caught out by a weird non-const issue which took a long time to track down.

I was using mat4.identity to initialise a few values in my application. Later on I called matrix_instance.translate/rotate/scale. This, as I'm sure you can guess, caused all matrices which had been initialised using mat4.identity to change. I definitely wasn't expecting this behaviour.

Is it possible to make mat*.identity a constant value? Or change it to a function which returns an identity matrix.

It's probably worth noting that I'm not that familiar with JS, and I'm very new to typescript. Perhaps a more experienced JS developed would know to expect this. Even so, the possibilty for mat4.identity to not be an identity matrix is a bit sneaky.

This may also apply to other identity values.

**Comment by matthiasferch** [comment]
The intended use of identity values is:

let m = mat.identity.copy();
m.rotate(..) etc.

But you're absolutely right, this is not safe. I'll update TSM to the latest TypeScript release and add const qualifiers as soon as I find the time.
